### ISSUE TITLE
Map loading blank

### ISSUE THREAD

**Issue by keepbees** [theopolisme/location-history-visualizer#33]
Hi,
Map loading blank from a takeout I did today, have tried a different browser just in case.
Just thought I'd let you know.
Thanks

**Comment by polarfoxDev** [comment]
same issue here in both current Firefox & MS Edge versions. The following error is thrown in the console:
```
Uncaught Error: Invalid LatLng object: (NaN, NaN)
    at new o.LatLng (leaflet.js:6:13842)
    at o.latLng (leaflet.js:6:14792)
    at o.LatLngBounds.contains (leaflet.js:6:16454)
    at e._redraw (leaflet.heat.min.js:11:2186)
    at leaflet.js:6:513
```

**Comment by polarfoxDev** [comment]
Seems to be related to #29
